# Generated by Django 4.0 on 2023-04-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargebeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=400)),
                ('item_price_id', models.CharField(max_length=400)),
                ('customer_id', models.CharField(max_length=400)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargebeeapp.user')),
            ],
        ),
    ]
