# Generated by Django 4.0 on 2023-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargebeeapp', '0003_alter_user_is_active_alter_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
